name: softgym
channels:
  - conda-forge 
  - defaults
dependencies:
  - python=3.7
  - opencv
  - numpy=1.17.2
  - imageio=2.6.1
  - imageio-ffmpeg
  - glob2=0.7
  - cmake=3.14.0
  - pybind11=2.4.3
  - moviepy
  - click
  - matplotlib
  - joblib
  - Pillow=8.4
  - plotly=4.14
  
  - sk-video
# SoftAgent specific
  - pip:
      - pyquaternion==0.9.5 
      # - opencv-python==5.1.1
      - gym==0.14.0
      - gtimer
      - torch==1.7.1
      - torchvision
      - dm-env
      - dm-tree
      - termcolor
      - Shapely==1.6.4.post2
      - git+https://github.com/1nadequacy/dmc2gym.git
      - scikit-image
      - kornia